/**
 * Compile-time checks for the LSP's concrete generated-symbol CST boundary.
 *
 * The assertions cover parser roots, recursive navigation, query captures, and
 * helper selectors without imposing exhaustive handling on feature walkers.
 */

import type { SatsumaCstType } from "@satsuma/core";
import type { Query } from "web-tree-sitter";
import { child, parseSource, queryCaptures } from "../src/parser-utils";

declare const query: Query;

const tree = parseSource("schema customer {}");
const rootType: SatsumaCstType = tree.rootNode.type;
const childType: SatsumaCstType | undefined = tree.rootNode.child(0)?.type;
const capturedType: SatsumaCstType | undefined = queryCaptures(query, tree.rootNode)[0]?.node.type;

child(tree.rootNode, "schema_block");

// Removed or invented grammar symbols must fail wherever LSP code selects CST nodes.
// @ts-expect-error "schema_declaration" is not generated by the Satsuma grammar.
child(tree.rootNode, "schema_declaration");

void rootType;
void childType;
void capturedType;
