#!/usr/bin/env node
/**
 * prebuild.js — Pre-build steps for the Satsuma CLI
 *
 * 1. Bakes the canonical reference/*.md sections into a TypeScript module so
 *    the CLI can ship the AI Agent Reference content without a runtime file
 *    read, and so `agent-reference` can serve the whole document, one
 *    profile, or one section from the same baked data (Feature 45).
 * 2. Copies WASM files into dist/ so the CLI can load them at runtime.
 *
 * Run automatically via `npm run prebuild` (called before `tsc`).
 */

import { createRequire } from "module";
import { writeFileSync, mkdirSync, copyFileSync, existsSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";
import { loadSections } from "../../../reference/compose.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, "..", "..", "..");
const cliRoot = join(__dirname, "..");
const require = createRequire(import.meta.url);

// ── Step 1: Bake the canonical reference/ sections ──

const outDir = join(cliRoot, "src", "generated");
const outPath = join(outDir, "agent-reference.ts");

// `loadSections()` returns manifest entries (id, file, profiles) with their
// reference/*.md content attached, in canonical document order. That order
// is preserved here, so composing every section back together reproduces
// the AI Agent Reference exactly — see agentReferenceCompose in
// commands/agent-reference.ts, and the byte-identity test in
// scripts/agent-reference-compose.test.mjs at the repo root.
const sections = loadSections();

mkdirSync(outDir, { recursive: true });

writeFileSync(
  outPath,
  `// Auto-generated by scripts/prebuild.js — do not edit manually.\n` +
    `// Source: reference/*.md (see reference/manifest.mjs for section order and profiles)\n\n` +
    `/** One canonical AI Agent Reference section, baked in at build time. */\n` +
    `export interface AgentReferenceSection {\n` +
    `  /** Stable identifier — the value \`--section\` accepts. */\n` +
    `  id: string;\n` +
    `  /** Task profiles (e.g. "write", "read") that include this section. */\n` +
    `  profiles: string[];\n` +
    `  /** The section's Markdown content, exactly as authored in reference/. */\n` +
    `  content: string;\n` +
    `}\n\n` +
    `/** Every section, in the canonical document order. */\n` +
    `export const agentReferenceSections: AgentReferenceSection[] = ${JSON.stringify(
      sections.map(({ id, profiles, content }) => ({ id, profiles, content })),
      null,
      2,
    )};\n`,
);

console.log(
  `prebuild: baked ${sections.length} reference/ sections → src/generated/agent-reference.ts`,
);

// ── Step 2: Copy WASM files into dist/ ──

const distDir = join(cliRoot, "dist");
mkdirSync(distDir, { recursive: true });

const wasmFiles = [
  {
    src: join(repoRoot, "tooling", "tree-sitter-satsuma", "tree-sitter-satsuma.wasm"),
    dest: join(distDir, "tree-sitter-satsuma.wasm"),
    label: "tree-sitter-satsuma.wasm",
  },
  {
    // web-tree-sitter 0.26+ renamed tree-sitter.wasm → web-tree-sitter.wasm, and
    // exports it as a subpath, so Node's resolver can find it wherever npm chose
    // to place the package. Under workspaces that is the hoisted root
    // node_modules, not this package's own — never join the path by hand.
    src: require.resolve("web-tree-sitter/web-tree-sitter.wasm"),
    dest: join(distDir, "web-tree-sitter.wasm"),
    label: "web-tree-sitter.wasm (runtime)",
  },
];

for (const { src, dest, label } of wasmFiles) {
  if (existsSync(src)) {
    copyFileSync(src, dest);
    console.log(`prebuild: copied ${label} → dist/`);
  } else {
    throw new Error(
      `prebuild: required ${label} not found at ${src}. ` +
        "Build tooling/tree-sitter-satsuma/tree-sitter-satsuma.wasm before packaging the CLI.",
    );
  }
}
