/**
 * Compile-time regression checks for viz-backend's shared CST contract.
 *
 * Both workspace indexing and model assembly consume these parser-utils types,
 * so one stale selector here proves either host fails fast on grammar drift.
 */

import type { SatsumaCstType, SyntaxNode, Tree } from "../src/parser-utils";
import { child } from "../src/parser-utils";

declare const node: SyntaxNode;
declare const tree: Tree;

const rootType: SatsumaCstType = tree.rootNode.type;
const childType: SatsumaCstType | undefined = node.child(0)?.type;
child(node, "mapping_block");

// Removed or invented symbols must fail in selectors shared by Node and browser hosts.
// @ts-expect-error "mapping_declaration" is not generated by the Satsuma grammar.
child(node, "mapping_declaration");

void rootType;
void childType;
